export type CuratedBook = {
  title: string;
  author: string;
  cover_url: string | null;
  open_library_id: string | null;
  total_pages: number | null;
  description: string;
  category: "anak" | "lokal";
  tags: string[];
};

// Covers via OpenLibrary ISBN API — null for books without known ISBN
const OL_COVER = (isbn: string) =>
  `https://covers.openlibrary.org/b/isbn/${isbn}-M.jpg`;

export const BUKU_ANAK: CuratedBook[] = [
  {
    title: "Harry Potter dan Batu Bertuah",
    author: "J.K. Rowling",
    cover_url: OL_COVER("9780439708180"),
    open_library_id: "OL82538W",
    total_pages: 368,
    description: "Harry Potter, bocah yatim piatu yang hidup bersama paman dan bibinya, menemukan bahwa dirinya adalah penyihir dan diundang masuk ke Sekolah Sihir Hogwarts.",
    category: "anak",
    tags: ["fantasi", "petualangan"],
  },
  {
    title: "Matilda",
    author: "Roald Dahl",
    cover_url: OL_COVER("9780142410370"),
    open_library_id: "OL26745W",
    total_pages: 240,
    description: "Matilda adalah gadis kecil yang sangat cerdas namun diabaikan keluarganya. Ia menemukan bahwa dirinya memiliki kekuatan telekinetik yang luar biasa.",
    category: "anak",
    tags: ["petualangan", "humor"],
  },
  {
    title: "Charlie dan Pabrik Cokelat",
    author: "Roald Dahl",
    cover_url: OL_COVER("9780142410318"),
    open_library_id: "OL36741W",
    total_pages: 176,
    description: "Charlie Bucket memenangkan Golden Ticket dan diajak masuk ke pabrik cokelat milik Willy Wonka yang penuh keajaiban.",
    category: "anak",
    tags: ["petualangan", "humor"],
  },
  {
    title: "Kancil dan Buaya",
    author: "Cerita Rakyat Indonesia",
    cover_url: null,
    open_library_id: null,
    total_pages: 48,
    description: "Kisah Si Kancil yang cerdik berhasil menyeberangi sungai dengan cara mengelabui para buaya. Cerita rakyat Nusantara yang mengajarkan akal dan kecerdikan.",
    category: "anak",
    tags: ["cerita rakyat", "fabel"],
  },
  {
    title: "Timun Mas",
    author: "Cerita Rakyat Indonesia",
    cover_url: null,
    open_library_id: null,
    total_pages: 48,
    description: "Seorang gadis bernama Timun Mas harus kabur dari raksasa menggunakan benda-benda ajaib pemberian ibunya. Legenda Jawa yang penuh pesan moral.",
    category: "anak",
    tags: ["cerita rakyat", "legenda"],
  },
  {
    title: "Bawang Merah dan Bawang Putih",
    author: "Cerita Rakyat Indonesia",
    cover_url: null,
    open_library_id: null,
    total_pages: 48,
    description: "Perbandingan antara Bawang Putih yang baik hati dengan Bawang Merah yang dengki. Cerita rakyat Indonesia yang mengajarkan kebaikan dan kejujuran.",
    category: "anak",
    tags: ["cerita rakyat", "moral"],
  },
  {
    title: "The Very Hungry Caterpillar",
    author: "Eric Carle",
    cover_url: OL_COVER("9780399226908"),
    open_library_id: "OL27258W",
    total_pages: 32,
    description: "Seekor ulat kecil yang lapar makan berbagai makanan selama seminggu sebelum akhirnya berubah menjadi kupu-kupu cantik.",
    category: "anak",
    tags: ["picture book", "edukasi"],
  },
  {
    title: "Laskar Pelangi Versi Anak",
    author: "Andrea Hirata",
    cover_url: null,
    open_library_id: null,
    total_pages: 120,
    description: "Adaptasi untuk anak-anak dari kisah persahabatan dan semangat sekolah sepuluh anak Belitung yang menginspirasi.",
    category: "anak",
    tags: ["Indonesia", "inspirasi"],
  },
  {
    title: "Si Kancil Anak Nakal",
    author: "Murti Bunanta",
    cover_url: null,
    open_library_id: null,
    total_pages: 56,
    description: "Petualangan Si Kancil yang nakal namun cerdas dalam menghadapi berbagai situasi di hutan Nusantara.",
    category: "anak",
    tags: ["fabel", "Indonesia"],
  },
  {
    title: "Malin Kundang",
    author: "Cerita Rakyat Sumatera Barat",
    cover_url: null,
    open_library_id: null,
    total_pages: 48,
    description: "Kisah anak durhaka yang dikutuk menjadi batu oleh ibunya. Legenda Sumatera Barat yang mengajarkan pentingnya bakti kepada orang tua.",
    category: "anak",
    tags: ["legenda", "moral"],
  },
  {
    title: "Aku Bisa! Seri Pertumbuhan Karakter",
    author: "Watiek Ideo",
    cover_url: null,
    open_library_id: null,
    total_pages: 32,
    description: "Seri buku anak tentang pembentukan karakter positif: jujur, disiplin, dan berani mencoba hal baru.",
    category: "anak",
    tags: ["edukasi", "karakter"],
  },
  {
    title: "Diary of a Wimpy Kid",
    author: "Jeff Kinney",
    cover_url: OL_COVER("9780810993136"),
    open_library_id: "OL12718837W",
    total_pages: 224,
    description: "Catatan harian Greg Heffley yang lucu tentang pengalamannya di sekolah menengah pertama, penuh kejadian konyol dan pelajaran hidup.",
    category: "anak",
    tags: ["humor", "remaja"],
  },
];

export const BUKU_LOKAL: CuratedBook[] = [
  {
    title: "Laskar Pelangi",
    author: "Andrea Hirata",
    cover_url: null,
    open_library_id: null,
    total_pages: 534,
    description: "Kisah sepuluh anak dari keluarga miskin di Belitung yang berjuang mendapatkan pendidikan terbaik dengan semangat yang tak pernah padam.",
    category: "lokal",
    tags: ["fiksi", "inspirasi", "pendidikan"],
  },
  {
    title: "Bumi Manusia",
    author: "Pramoedya Ananta Toer",
    cover_url: null,
    open_library_id: null,
    total_pages: 368,
    description: "Novel pertama Tetralogi Buru. Kisah Minke, pemuda Jawa terpelajar yang jatuh cinta pada Annelies di tengah kolonialisme Belanda.",
    category: "lokal",
    tags: ["fiksi", "sejarah", "sastra"],
  },
  {
    title: "Negeri 5 Menara",
    author: "Ahmad Fuadi",
    cover_url: null,
    open_library_id: null,
    total_pages: 423,
    description: "Alif Fikri, seorang anak Minang, mengikuti pendidikan di pesantren modern Gontor dan menemukan mimpi besar bersama sahabat-sahabatnya.",
    category: "lokal",
    tags: ["fiksi", "inspirasi", "pendidikan"],
  },
  {
    title: "Perahu Kertas",
    author: "Dewi Lestari (Dee)",
    cover_url: null,
    open_library_id: null,
    total_pages: 444,
    description: "Kisah cinta Kugy dan Keenan yang ditemukan kembali lewat perahu kertas mimpi dan seni, menembus waktu dan jarak.",
    category: "lokal",
    tags: ["fiksi", "romance"],
  },
  {
    title: "Supernova: Ksatria, Puteri, dan Bintang Jatuh",
    author: "Dewi Lestari (Dee)",
    cover_url: null,
    open_library_id: null,
    total_pages: 328,
    description: "Novel sains populer Indonesia yang memadukan fisika kuantum, spiritualitas, dan kisah cinta yang kompleks.",
    category: "lokal",
    tags: ["fiksi", "sains", "filsafat"],
  },
  {
    title: "Dilan: Dia adalah Dilanku Tahun 1990",
    author: "Pidi Baiq",
    cover_url: null,
    open_library_id: null,
    total_pages: 231,
    description: "Kisah cinta SMA di Bandung tahun 1990 antara Milea dan Dilan, pemuda geng motor yang romantis dan jenaka.",
    category: "lokal",
    tags: ["romance", "remaja"],
  },
  {
    title: "Tentang Kamu",
    author: "Tere Liye",
    cover_url: null,
    open_library_id: null,
    total_pages: 524,
    description: "Perjalanan pengacara muda menemukan kisah hidup Sri Ningsih, wanita Indonesia yang menjalani berbagai babak kehidupan di berbagai belahan dunia.",
    category: "lokal",
    tags: ["fiksi", "drama"],
  },
  {
    title: "Cantik Itu Luka",
    author: "Eka Kurniawan",
    cover_url: null,
    open_library_id: null,
    total_pages: 505,
    description: "Kisah keluarga Dewi Ayu dan tiga putrinya yang terjerat kutukan kecantikan, berlatar sejarah Indonesia dari masa penjajahan hingga kemerdekaan.",
    category: "lokal",
    tags: ["sastra", "sejarah", "fiksi"],
  },
  {
    title: "5 Cm",
    author: "Donny Dhirgantoro",
    cover_url: null,
    open_library_id: null,
    total_pages: 381,
    description: "Lima sahabat menapaki puncak Mahameru dengan tekad bahwa impian harus diletakkan di depan mata, sejauh 5 cm dari kening.",
    category: "lokal",
    tags: ["petualangan", "persahabatan"],
  },
  {
    title: "Pulang",
    author: "Leila S. Chudori",
    cover_url: null,
    open_library_id: null,
    total_pages: 464,
    description: "Kisah para eksil Indonesia di Paris yang tidak bisa pulang ke tanah air akibat tragedi 1965, dituturkan lintas generasi.",
    category: "lokal",
    tags: ["sastra", "sejarah", "fiksi"],
  },
  {
    title: "Ayah",
    author: "Andrea Hirata",
    cover_url: null,
    open_library_id: null,
    total_pages: 412,
    description: "Kisah cinta seorang ayah kepada putrinya, Amiru, yang ia besarkan dengan cara yang unik dan penuh kasih di tanah Belitung.",
    category: "lokal",
    tags: ["fiksi", "keluarga"],
  },
  {
    title: "Atomic Habits (Terjemahan)",
    author: "James Clear",
    cover_url: OL_COVER("9780735211292"),
    open_library_id: "OL20082940W",
    total_pages: 320,
    description: "Panduan praktis membentuk kebiasaan baik dan menghilangkan kebiasaan buruk melalui perubahan kecil yang konsisten.",
    category: "lokal",
    tags: ["non-fiksi", "pengembangan diri"],
  },
  {
    title: "Rich Dad Poor Dad (Terjemahan)",
    author: "Robert T. Kiyosaki",
    cover_url: OL_COVER("9781612680194"),
    open_library_id: "OL2682688W",
    total_pages: 336,
    description: "Pelajaran keuangan yang diajarkan oleh dua ayah dengan filosofi berbeda tentang uang, investasi, dan kebebasan finansial.",
    category: "lokal",
    tags: ["non-fiksi", "bisnis", "keuangan"],
  },

  /* ─── Sastra Indonesia Lanjutan ─── */
  {
    title: "Sang Pemimpi",
    author: "Andrea Hirata",
    cover_url: null, open_library_id: null, total_pages: 292,
    description: "Ikal dan Arai, dua sepupu dari Belitung, nekat merantau ke Perancis hanya bermodalkan mimpi dan tekad baja.",
    category: "lokal",
    tags: ["fiksi", "inspirasi", "persahabatan"],
  },
  {
    title: "Edensor",
    author: "Andrea Hirata",
    cover_url: null, open_library_id: null, total_pages: 294,
    description: "Ikal menjelajahi Eropa dengan Arai, mencari jati diri dan cinta, sembari mengejar impian menginjakkan kaki di Inggris.",
    category: "lokal",
    tags: ["fiksi", "petualangan", "inspirasi"],
  },
  {
    title: "Maryamah Karpov",
    author: "Andrea Hirata",
    cover_url: null, open_library_id: null, total_pages: 494,
    description: "Penutup tetralogi Laskar Pelangi. Ikal kembali ke Belitung dan nekat melintasi samudra untuk menemukan cinta pertamanya.",
    category: "lokal",
    tags: ["fiksi", "petualangan"],
  },
  {
    title: "Ronggeng Dukuh Paruk",
    author: "Ahmad Tohari",
    cover_url: null, open_library_id: null, total_pages: 408,
    description: "Kisah Srintil, perempuan ronggeng dari Dukuh Paruk, yang terjebak di antara seni, cinta, dan gejolak politik Indonesia.",
    category: "lokal",
    tags: ["sastra", "sejarah", "fiksi"],
  },
  {
    title: "Saman",
    author: "Ayu Utami",
    cover_url: null, open_library_id: null, total_pages: 196,
    description: "Novel yang memadukan erotisme, spiritualitas, dan kritik sosial — mengguncang sastra Indonesia saat pertama terbit.",
    category: "lokal",
    tags: ["sastra", "fiksi", "sosial"],
  },
  {
    title: "Lelaki Harimau",
    author: "Eka Kurniawan",
    cover_url: null, open_library_id: null, total_pages: 192,
    description: "Margio membunuh tetangganya karena harimau dalam dirinya. Novel noir Indonesia yang menggabungkan realisme magis dan tragedi.",
    category: "lokal",
    tags: ["sastra", "fiksi", "misteri"],
  },
  {
    title: "Anak Semua Bangsa",
    author: "Pramoedya Ananta Toer",
    cover_url: null, open_library_id: null, total_pages: 352,
    description: "Minke melanjutkan perjuangannya melawan kolonialisme, kini dengan wawasan yang lebih luas tentang bangsa dan identitas.",
    category: "lokal",
    tags: ["sastra", "sejarah", "fiksi"],
  },
  {
    title: "Jejak Langkah",
    author: "Pramoedya Ananta Toer",
    cover_url: null, open_library_id: null, total_pages: 640,
    description: "Minke tumbuh menjadi jurnalis dan pergerakan nasional mulai bangkit. Buku ketiga Tetralogi Buru.",
    category: "lokal",
    tags: ["sastra", "sejarah", "fiksi"],
  },
  {
    title: "Bukan Pasar Malam",
    author: "Pramoedya Ananta Toer",
    cover_url: null, open_library_id: null, total_pages: 128,
    description: "Novel pendek autobiografis yang emosional tentang seorang anak yang pulang kampung menemani ayahnya yang sekarat.",
    category: "lokal",
    tags: ["sastra", "keluarga", "fiksi"],
  },
  {
    title: "Rindu",
    author: "Tere Liye",
    cover_url: null, open_library_id: null, total_pages: 544,
    description: "Kisah berlatar kapal uap 1938 membawa rombongan haji Indonesia. Lima pertanyaan besar tentang kehidupan, takdir, dan Tuhan.",
    category: "lokal",
    tags: ["fiksi", "sejarah", "spiritualitas"],
  },
  {
    title: "Hujan",
    author: "Tere Liye",
    cover_url: null, open_library_id: null, total_pages: 320,
    description: "Lail dan Soke Bahtera menjalani persahabatan di dunia masa depan yang baru bangkit setelah bencana besar.",
    category: "lokal",
    tags: ["fiksi", "sains", "romance"],
  },
  {
    title: "Daun yang Jatuh Tak Pernah Membenci Angin",
    author: "Tere Liye",
    cover_url: null, open_library_id: null, total_pages: 264,
    description: "Tania jatuh cinta pada Danar, pria yang menyelamatkan keluarganya dari kemiskinan. Kisah cinta yang menyentuh tentang keikhlasan.",
    category: "lokal",
    tags: ["fiksi", "romance", "keluarga"],
  },
  {
    title: "Bidadari-Bidadari Surga",
    author: "Tere Liye",
    cover_url: null, open_library_id: null, total_pages: 348,
    description: "Kisah Laisa, kakak tertua yang mengorbankan segalanya demi adik-adiknya meraih pendidikan dan impian.",
    category: "lokal",
    tags: ["fiksi", "keluarga", "inspirasi"],
  },
  {
    title: "Ayahku Bukan Pembohong",
    author: "Tere Liye",
    cover_url: null, open_library_id: null, total_pages: 304,
    description: "Dam tumbuh besar mendengar kisah-kisah luar biasa dari ayahnya. Apakah semua itu nyata, atau hanya dongeng?",
    category: "lokal",
    tags: ["fiksi", "keluarga"],
  },
  {
    title: "Garis Waktu",
    author: "Fiersa Besari",
    cover_url: null, open_library_id: null, total_pages: 240,
    description: "Kumpulan tulisan tentang patah hati, harapan, dan kebebasan. Fiersa Besari dalam bahasa yang dekat di hati anak muda.",
    category: "lokal",
    tags: ["puisi", "non-fiksi", "pengembangan diri"],
  },
  {
    title: "Konspirasi Alam Semesta",
    author: "Fiersa Besari",
    cover_url: null, open_library_id: null, total_pages: 256,
    description: "Novel perdana Fiersa Besari. Kisah seorang musisi jalanan yang mengejar mimpi dan menemukan cinta di jalan yang tidak terduga.",
    category: "lokal",
    tags: ["fiksi", "romance", "musik"],
  },
  {
    title: "Hujan Bulan Juni",
    author: "Sapardi Djoko Damono",
    cover_url: null, open_library_id: null, total_pages: 148,
    description: "Kumpulan puisi ikonik SDD yang lembut dan mendalam. Dari 'Aku Ingin' hingga sajak-sajak yang sudah menjadi warisan sastra Indonesia.",
    category: "lokal",
    tags: ["puisi", "sastra"],
  },
  {
    title: "Catatan Seorang Demonstran",
    author: "Soe Hok Gie",
    cover_url: null, open_library_id: null, total_pages: 254,
    description: "Catatan harian aktivis mahasiswa Indonesia 1960-an yang kritis, idealis, dan berani bersuara di masa Orde Lama.",
    category: "lokal",
    tags: ["non-fiksi", "sejarah", "biografi"],
  },
  {
    title: "Manusia Setengah Salmon",
    author: "Raditya Dika",
    cover_url: null, open_library_id: null, total_pages: 224,
    description: "Kumpulan esai komedi absurd tentang hidup, cinta, dan keputusan-keputusan bodoh yang bisa sangat manusiawi.",
    category: "lokal",
    tags: ["humor", "non-fiksi"],
  },
  {
    title: "Para Priyayi",
    author: "Umar Kayam",
    cover_url: null, open_library_id: null, total_pages: 400,
    description: "Saga keluarga priyayi Jawa dari era kolonial hingga pasca-kemerdekaan, menelusuri perubahan nilai dan identitas.",
    category: "lokal",
    tags: ["sastra", "sejarah", "keluarga"],
  },
  {
    title: "Keajaiban Toko Kelontong Namiya",
    author: "Keigo Higashino",
    cover_url: OL_COVER("9780143127871"), open_library_id: "OL26388143W", total_pages: 360,
    description: "Toko kelontong tua menerima surat dari masa depan. Kisah mengharukan tentang pilihan, penyesalan, dan harapan.",
    category: "lokal",
    tags: ["fiksi", "misteri", "terjemahan"],
  },
  {
    title: "Winter in Tokyo",
    author: "Ilana Tan",
    cover_url: null, open_library_id: null, total_pages: 344,
    description: "Keiko dan Kazuto bertetangga di Tokyo musim dingin. Roman manis dengan latar Jepang yang hangat dan melankolis.",
    category: "lokal",
    tags: ["romance", "fiksi"],
  },

  /* ─── Non-Fiksi & Pengembangan Diri Indonesia ─── */
  {
    title: "Filosofi Teras",
    author: "Henry Manampiring",
    cover_url: null, open_library_id: null, total_pages: 296,
    description: "Panduan praktis Stoisisme gaya Indonesia — filosofi Yunani-Romawi kuno yang relevan untuk menghadapi kecemasan dan tekanan hidup modern.",
    category: "lokal",
    tags: ["non-fiksi", "filsafat", "pengembangan diri"],
  },
  {
    title: "Multi Identitas Zahid",
    author: "Zahid",
    cover_url: null, open_library_id: null, total_pages: 250,
    description: "Eksplorasi mendalam tentang identitas berlapis yang dimiliki manusia modern — antara keluarga, karier, budaya, dan nilai yang kita pegang.",
    category: "lokal",
    tags: ["non-fiksi", "pengembangan diri"],
  },
  {
    title: "Makanya Mikir!",
    author: "Pandji Pragiwaksono",
    cover_url: null, open_library_id: null, total_pages: 256,
    description: "Pandji mengajak pembaca berpikir kritis tentang isu-isu Indonesia dengan humor dan kejujuran yang segar.",
    category: "lokal",
    tags: ["non-fiksi", "sosial", "humor"],
  },
  {
    title: "The Intimate Story of Muhammad",
    author: "Hawariyun",
    cover_url: null, open_library_id: null, total_pages: 380,
    description: "Kisah Nabi Muhammad saw yang dituturkan secara intim dan manusiawi — mendekatkan pembaca pada sosok Rasul sebagai manusia sempurna.",
    category: "lokal",
    tags: ["non-fiksi", "spiritualitas", "biografi", "agama"],
  },

  /* ─── Terjemahan Populer ─── */
  {
    title: "Sang Alkemis",
    author: "Paulo Coelho",
    cover_url: OL_COVER("9780062315007"), open_library_id: "OL7975735W", total_pages: 208,
    description: "Santiago, penggembala muda Spanyol, menempuh perjalanan ke Mesir untuk menemukan harta karun dan menemukan dirinya sendiri.",
    category: "lokal",
    tags: ["fiksi", "filsafat", "inspirasi", "terjemahan"],
  },
  {
    title: "Sapiens: Riwayat Singkat Umat Manusia",
    author: "Yuval Noah Harari",
    cover_url: OL_COVER("9780062316097"), open_library_id: "OL17595553W", total_pages: 416,
    description: "Perjalanan umat manusia dari Homo sapiens primitif hingga penguasa bumi, dituturkan dengan riset mendalam dan cara pandang segar.",
    category: "lokal",
    tags: ["non-fiksi", "sejarah", "sains", "terjemahan"],
  },
  {
    title: "Homo Deus",
    author: "Yuval Noah Harari",
    cover_url: OL_COVER("9780062464316"), open_library_id: "OL17784437W", total_pages: 448,
    description: "Apa agenda manusia berikutnya setelah mengatasi kelaparan, perang, dan wabah? Harari meramalkan masa depan umat manusia.",
    category: "lokal",
    tags: ["non-fiksi", "sains", "futuristik", "terjemahan"],
  },
  {
    title: "Ikigai: Rahasia Hidup Bahagia Orang Jepang",
    author: "Héctor García & Francesc Miralles",
    cover_url: OL_COVER("9780143130727"), open_library_id: "OL25422228W", total_pages: 208,
    description: "Rahasia panjang umur dan kebahagiaan penduduk Okinawa — menemukan tujuan hidup (ikigai) di antara passion, misi, dan kebutuhan dunia.",
    category: "lokal",
    tags: ["non-fiksi", "pengembangan diri", "terjemahan"],
  },
  {
    title: "Sebuah Seni untuk Bersikap Bodo Amat",
    author: "Mark Manson",
    cover_url: OL_COVER("9780062457714"), open_library_id: "OL20082940W", total_pages: 272,
    description: "Pandangan kontra-intuitif tentang hidup baik: pilih dengan cermat apa yang layak kamu pedulikan, dan biarkan sisanya.",
    category: "lokal",
    tags: ["non-fiksi", "pengembangan diri", "terjemahan"],
  },
  {
    title: "The 7 Habits of Highly Effective People",
    author: "Stephen R. Covey",
    cover_url: OL_COVER("9780743269513"), open_library_id: "OL2631228W", total_pages: 372,
    description: "Tujuh kebiasaan yang membentuk karakter dan efektivitas — dari proaktif, memulai dengan tujuan akhir, hingga mengasah kemampuan terus-menerus.",
    category: "lokal",
    tags: ["non-fiksi", "pengembangan diri", "terjemahan"],
  },
  {
    title: "Start with Why",
    author: "Simon Sinek",
    cover_url: OL_COVER("9781591846444"), open_library_id: "OL24756820W", total_pages: 256,
    description: "Mengapa sebagian pemimpin dan organisasi menginspirasi semua orang sementara yang lain tidak? Jawabannya: mulailah dari 'mengapa'.",
    category: "lokal",
    tags: ["non-fiksi", "bisnis", "kepemimpinan", "terjemahan"],
  },
  {
    title: "Outliers: The Story of Success",
    author: "Malcolm Gladwell",
    cover_url: OL_COVER("9780316017930"), open_library_id: "OL24195438W", total_pages: 320,
    description: "Apa yang benar-benar membedakan orang sukses? Gladwell mengungkap faktor tersembunyi di balik Bill Gates, The Beatles, dan juara-juara dunia.",
    category: "lokal",
    tags: ["non-fiksi", "psikologi", "bisnis", "terjemahan"],
  },
  {
    title: "Deep Work",
    author: "Cal Newport",
    cover_url: OL_COVER("9781455586691"), open_library_id: "OL21992968W", total_pages: 304,
    description: "Kemampuan fokus tanpa distraksi adalah supervpower era digital. Newport mengajarkan cara melatih dan memanfaatkannya.",
    category: "lokal",
    tags: ["non-fiksi", "produktivitas", "terjemahan"],
  },
  {
    title: "Mindset: The New Psychology of Success",
    author: "Carol S. Dweck",
    cover_url: OL_COVER("9780345472328"), open_library_id: "OL17590611W", total_pages: 320,
    description: "Perbedaan antara fixed mindset dan growth mindset, dan bagaimana mengubah cara pandang untuk mencapai potensi penuh.",
    category: "lokal",
    tags: ["non-fiksi", "psikologi", "pengembangan diri", "terjemahan"],
  },
  {
    title: "Essentialism: The Disciplined Pursuit of Less",
    author: "Greg McKeown",
    cover_url: OL_COVER("9780804137386"), open_library_id: "OL26359488W", total_pages: 272,
    description: "Lakukan lebih sedikit, tapi lebih baik. Panduan sistematis memilih hanya hal yang benar-benar penting.",
    category: "lokal",
    tags: ["non-fiksi", "produktivitas", "pengembangan diri", "terjemahan"],
  },
  {
    title: "Man's Search for Meaning",
    author: "Viktor E. Frankl",
    cover_url: OL_COVER("9780807014295"), open_library_id: "OL1726677W", total_pages: 200,
    description: "Psikiater Austria yang selamat dari kamp Nazi Auschwitz menjelaskan bahwa makna — bukan kebahagiaan — adalah tujuan utama manusia.",
    category: "lokal",
    tags: ["non-fiksi", "filsafat", "biografi", "terjemahan"],
  },
  {
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    cover_url: OL_COVER("9780374275631"), open_library_id: "OL24947540W", total_pages: 512,
    description: "Pemenang Nobel menjelaskan dua sistem berpikir kita: Sistem 1 yang cepat dan intuitif, dan Sistem 2 yang lambat dan rasional.",
    category: "lokal",
    tags: ["non-fiksi", "psikologi", "sains", "terjemahan"],
  },
  {
    title: "Zero to One",
    author: "Peter Thiel",
    cover_url: OL_COVER("9780804139021"), open_library_id: "OL26416164W", total_pages: 224,
    description: "Pendiri PayPal berbagi cara berpikir tentang inovasi: membuat sesuatu yang belum pernah ada lebih berharga dari meniru.",
    category: "lokal",
    tags: ["non-fiksi", "bisnis", "startup", "terjemahan"],
  },
  {
    title: "The Power of Now",
    author: "Eckhart Tolle",
    cover_url: OL_COVER("9781577314806"), open_library_id: "OL9965655W", total_pages: 224,
    description: "Panduan transformatif untuk hidup di momen ini — melepaskan pikiran masa lalu dan kecemasan masa depan.",
    category: "lokal",
    tags: ["non-fiksi", "spiritualitas", "pengembangan diri", "terjemahan"],
  },
  {
    title: "Never Split the Difference",
    author: "Chris Voss",
    cover_url: OL_COVER("9780062407801"), open_library_id: "OL27180560W", total_pages: 288,
    description: "Mantan negosiator sandera FBI mengajarkan taktik negosiasi yang bisa dipakai dalam kehidupan sehari-hari.",
    category: "lokal",
    tags: ["non-fiksi", "bisnis", "komunikasi", "terjemahan"],
  },
  {
    title: "The Art of War",
    author: "Sun Tzu",
    cover_url: OL_COVER("9781590302255"), open_library_id: "OL20673W", total_pages: 112,
    description: "Traktat militer 2.500 tahun yang masih relevan — seni memenangkan konflik dengan strategi, bukan kekerasan semata.",
    category: "lokal",
    tags: ["non-fiksi", "strategi", "terjemahan"],
  },
  {
    title: "Sang Nabi",
    author: "Kahlil Gibran",
    cover_url: OL_COVER("9780394404288"), open_library_id: "OL42W", total_pages: 96,
    description: "Almustafa menjawab pertanyaan penduduk tentang cinta, pernikahan, anak, kerja, dan kematian dalam kata-kata yang puitis abadi.",
    category: "lokal",
    tags: ["fiksi", "puisi", "filsafat", "terjemahan"],
  },
  {
    title: "The Alchemist (Inggris)",
    author: "Paulo Coelho",
    cover_url: OL_COVER("9780062315007"), open_library_id: "OL7975735W", total_pages: 208,
    description: "The Alchemist in its original English form — the universal story of following one's Personal Legend.",
    category: "lokal",
    tags: ["fiksi", "inspirasi", "terjemahan"],
  },

  /* ─── Fiksi Indonesia Tambahan ─── */
  {
    title: "Rembulan Tenggelam di Wajahmu",
    author: "Tere Liye",
    cover_url: null, open_library_id: null, total_pages: 400,
    description: "Rey, seorang yatim piatu yang tumbuh penuh kepahitan, mendapat kesempatan menjawab lima pertanyaan besar hidupnya sebelum ajal menjemput.",
    category: "lokal",
    tags: ["fiksi", "spiritualitas", "drama"],
  },
  {
    title: "Hafalan Shalat Delisa",
    author: "Tere Liye",
    cover_url: null, open_library_id: null, total_pages: 268,
    description: "Delisa, bocah 6 tahun dari Aceh, kehilangan segalanya dalam tsunami 2004 — namun semangatnya untuk menghafal shalat tak pernah padam.",
    category: "lokal",
    tags: ["fiksi", "keluarga", "spiritualitas", "sejarah"],
  },
  {
    title: "Kau, Aku, dan Sepucuk Angpau Merah",
    author: "Tere Liye",
    cover_url: null, open_library_id: null, total_pages: 512,
    description: "Borno dan Mei, dua anak muda di tepi Sungai Kapuas Kalimantan, terhubung lewat sebuah angpau merah dan takdir yang tak terduga.",
    category: "lokal",
    tags: ["fiksi", "romance", "budaya"],
  },
  {
    title: "Bumi",
    author: "Tere Liye",
    cover_url: null, open_library_id: null, total_pages: 440,
    description: "Raib, gadis 15 tahun, tiba-tiba menghilang saat bercermin. Petualangan seru di dunia paralel bersama Seli dan Ali dimulai.",
    category: "lokal",
    tags: ["fiksi", "petualangan", "fantasi", "remaja"],
  },
  {
    title: "Ranah 3 Warna",
    author: "Ahmad Fuadi",
    cover_url: null, open_library_id: null, total_pages: 473,
    description: "Alif meninggalkan Gontor dan mengejar mimpi kuliah di Bandung, lalu hijrah ke Kanada — perjuangan keras anak Minang menembus batas dunia.",
    category: "lokal",
    tags: ["fiksi", "inspirasi", "pendidikan", "petualangan"],
  },
  {
    title: "Rantau 1 Muara",
    author: "Ahmad Fuadi",
    cover_url: null, open_library_id: null, total_pages: 424,
    description: "Alif akhirnya tiba di New York mengejar beasiswa bergengsi. Penutup Trilogi Negeri 5 Menara yang menyentuh tentang ketekunan dan cinta.",
    category: "lokal",
    tags: ["fiksi", "inspirasi", "pendidikan"],
  },
  {
    title: "Sirkus Pohon",
    author: "Andrea Hirata",
    cover_url: null, open_library_id: null, total_pages: 383,
    description: "Kisah Sobri yang jatuh cinta pada Dinda, putri seorang bos sirkus di kampung Melayu yang penuh warna dan keriuhan.",
    category: "lokal",
    tags: ["fiksi", "romance", "humor", "budaya"],
  },
  {
    title: "Orang-Orang Biasa",
    author: "Andrea Hirata",
    cover_url: null, open_library_id: null, total_pages: 312,
    description: "Sepuluh orang biasa dengan profesi rendahan bersatu merampok bank demi membiayai pendidikan anak mereka. Komedi kriminal penuh hati.",
    category: "lokal",
    tags: ["fiksi", "humor", "persahabatan", "sosial"],
  },
  {
    title: "Larung",
    author: "Ayu Utami",
    cover_url: null, open_library_id: null, total_pages: 228,
    description: "Sekuel Saman. Saman dan empat perempuan temannya melanjutkan perjuangan melawan rezim, cinta, dan trauma yang tak kunjung usai.",
    category: "lokal",
    tags: ["sastra", "fiksi", "sosial"],
  },
  {
    title: "Negeri Van Oranje",
    author: "Wahyuningrat, D. Purnomo, A. Widiarsa, R.P. Permana",
    cover_url: null, open_library_id: null, total_pages: 424,
    description: "Lima mahasiswa Indonesia berkuliah di Belanda dan menjalani petualangan cinta, budaya, dan persahabatan di negeri kincir angin.",
    category: "lokal",
    tags: ["fiksi", "petualangan", "romance", "persahabatan"],
  },
  {
    title: "Senja dan Fajar",
    author: "Boy Candra",
    cover_url: null, open_library_id: null, total_pages: 230,
    description: "Dua jiwa yang saling bertemu di sela kesepian — kisah cinta yang sederhana, hangat, dan dekat di hati anak muda Indonesia.",
    category: "lokal",
    tags: ["fiksi", "romance"],
  },
  {
    title: "Perempuan Berkalung Sorban",
    author: "Abidah El Khalieqy",
    cover_url: null, open_library_id: null, total_pages: 280,
    description: "Annisa tumbuh di pesantren konservatif dan berjuang menuntut kesetaraan hak perempuan di tengah budaya patriarki yang kuat.",
    category: "lokal",
    tags: ["fiksi", "sosial", "feminisme", "agama"],
  },
  {
    title: "Madre",
    author: "Dewi Lestari (Dee)",
    cover_url: null, open_library_id: null, total_pages: 184,
    description: "Kumpulan cerita pendek Dee yang eksperimental — dari cerita roti sourdough warisan leluhur hingga kisah fiksi sains yang menawan.",
    category: "lokal",
    tags: ["fiksi", "cerpen", "sastra"],
  },
  {
    title: "Summer in Seoul",
    author: "Ilana Tan",
    cover_url: null, open_library_id: null, total_pages: 288,
    description: "Sandy bertemu Jung Tae-yang di Seoul musim panas. Roman manis berlatar Korea yang hangat dan menggemaskan.",
    category: "lokal",
    tags: ["romance", "fiksi"],
  },

  /* ─── Non-Fiksi Indonesia Tambahan ─── */
  {
    title: "Habibie & Ainun",
    author: "B.J. Habibie",
    cover_url: null, open_library_id: null, total_pages: 323,
    description: "Memoar cinta Presiden ke-3 RI kepada istrinya Ainun — kisah nyata yang membuktikan bahwa cinta sejati melampaui segala capaian.",
    category: "lokal",
    tags: ["non-fiksi", "biografi", "cinta", "sejarah"],
  },
  {
    title: "Berani Tidak Disukai",
    author: "Fumitake Koga & Ichiro Kishimi",
    cover_url: OL_COVER("9781501197284"), open_library_id: null, total_pages: 272,
    description: "Filsafat Adler dikemas dalam dialog Socrates: keberanian untuk hidup bebas dari pengakuan orang lain dan masa lalu yang membelenggu.",
    category: "lokal",
    tags: ["non-fiksi", "filsafat", "pengembangan diri", "terjemahan"],
  },
  {
    title: "Bersyukur Tanpa Batas",
    author: "Arvan Pradiansyah",
    cover_url: null, open_library_id: null, total_pages: 240,
    description: "Panduan menemukan kebahagiaan sejati lewat rasa syukur — cara pandang yang mengubah keluhan menjadi kekuatan.",
    category: "lokal",
    tags: ["non-fiksi", "pengembangan diri", "spiritualitas"],
  },
  {
    title: "Self Driving",
    author: "Rene Suhardono",
    cover_url: null, open_library_id: null, total_pages: 204,
    description: "Panduan menemukan pekerjaan yang benar-benar bermakna — bukan sekadar karier, tapi hidup yang kamu pilih dengan sadar.",
    category: "lokal",
    tags: ["non-fiksi", "karier", "pengembangan diri"],
  },

  /* ─── Sastra Jepang ─── */
  {
    title: "Norwegian Wood",
    author: "Haruki Murakami",
    cover_url: OL_COVER("9780375704024"), open_library_id: "OL273882W", total_pages: 296,
    description: "Toru Watanabe mengenang cintanya pada Naoko — gadis rapuh yang terjebak antara hidup dan kematian di Tokyo tahun 1960-an.",
    category: "lokal",
    tags: ["fiksi", "sastra", "romance", "terjemahan"],
  },
  {
    title: "Kafka on the Shore",
    author: "Haruki Murakami",
    cover_url: OL_COVER("9780099494094"), open_library_id: "OL7981479W", total_pages: 505,
    description: "Kafka Tamura melarikan diri dari rumah, sementara Nakata si tua bodoh mencari sesuatu yang tak ia mengerti. Dua kisah yang berjalin secara misterius.",
    category: "lokal",
    tags: ["fiksi", "sastra", "misteri", "surreal", "terjemahan"],
  },
  {
    title: "1Q84",
    author: "Haruki Murakami",
    cover_url: OL_COVER("9780307593313"), open_library_id: "OL16084990W", total_pages: 944,
    description: "Aomame dan Tengo hidup dalam Tokyo 1984 yang perlahan berubah menjadi dunia paralel bernama 1Q84, dengan dua bulan di langit malam.",
    category: "lokal",
    tags: ["fiksi", "sastra", "surreal", "terjemahan"],
  },
  {
    title: "Kitchen",
    author: "Banana Yoshimoto",
    cover_url: OL_COVER("9780802150868"), open_library_id: "OL2627024W", total_pages: 152,
    description: "Mikage menemukan ketenangan hidup hanya di dapur setelah kehilangan neneknya. Novela Jepang yang lembut, menyentuh, dan penuh kehangatan.",
    category: "lokal",
    tags: ["fiksi", "sastra", "keluarga", "terjemahan"],
  },
  {
    title: "Totto-chan: Gadis Cilik di Tepi Jendela",
    author: "Tetsuko Kuroyanagi",
    cover_url: OL_COVER("9781568360911"), open_library_id: "OL3327941W", total_pages: 231,
    description: "Totto-chan dikeluarkan dari sekolah dasar karena terlalu aktif. Di sekolah baru dalam gerbong kereta, ia menemukan metode belajar yang benar-benar bebas.",
    category: "lokal",
    tags: ["non-fiksi", "biografi", "pendidikan", "terjemahan"],
  },
  {
    title: "Convenience Store Woman",
    author: "Sayaka Murata",
    cover_url: OL_COVER("9780802128898"), open_library_id: "OL27292069W", total_pages: 176,
    description: "Keiko hidup bahagia sebagai kasir minimarket selama 18 tahun — satire tajam tentang tekanan sosial untuk 'normal' di Jepang.",
    category: "lokal",
    tags: ["fiksi", "sastra", "sosial", "terjemahan"],
  },
  {
    title: "Confessions",
    author: "Kanae Minato",
    cover_url: OL_COVER("9780316200929"), open_library_id: "OL24206553W", total_pages: 240,
    description: "Seorang guru SMP mengumumkan rencana balas dendam terhadap murid yang membunuh anaknya. Thriller psikologis Jepang yang menghantui.",
    category: "lokal",
    tags: ["fiksi", "thriller", "misteri", "terjemahan"],
  },
  {
    title: "Kokoro",
    author: "Natsume Soseki",
    cover_url: OL_COVER("9780895269010"), open_library_id: "OL96479W", total_pages: 248,
    description: "Sensei — tokoh misterius yang menyimpan rahasia berat — mengungkap kebenaran hidupnya dalam surat yang menggetarkan jiwa.",
    category: "lokal",
    tags: ["sastra", "fiksi", "filsafat", "terjemahan"],
  },

  /* ─── Sastra Dunia Klasik ─── */
  {
    title: "1984",
    author: "George Orwell",
    cover_url: OL_COVER("9780451524935"), open_library_id: "OL1168007W", total_pages: 328,
    description: "Winston Smith hidup di bawah pengawasan Big Brother yang omnipresent. Distopia paling ikonik sepanjang masa tentang kebebasan dan kontrol.",
    category: "lokal",
    tags: ["fiksi", "distopia", "sastra", "terjemahan"],
  },
  {
    title: "Animal Farm",
    author: "George Orwell",
    cover_url: OL_COVER("9780451526342"), open_library_id: "OL1168008W", total_pages: 144,
    description: "Para hewan mengambil alih ladang dari manusia — alegori tajam tentang revolusi yang berujung pada tirani yang lebih buruk.",
    category: "lokal",
    tags: ["fiksi", "alegori", "politik", "sastra", "terjemahan"],
  },
  {
    title: "The Little Prince",
    author: "Antoine de Saint-Exupéry",
    cover_url: OL_COVER("9780156012195"), open_library_id: "OL35120W", total_pages: 96,
    description: "Pangeran kecil dari asteroid kecil bertemu pilot yang terdampar di gurun Sahara. Kisah filosofis tentang persahabatan, cinta, dan makna hidup.",
    category: "lokal",
    tags: ["fiksi", "filsafat", "klasik", "terjemahan"],
  },
  {
    title: "Crime and Punishment",
    author: "Fyodor Dostoevsky",
    cover_url: OL_COVER("9780486415871"), open_library_id: "OL166894W", total_pages: 576,
    description: "Raskolnikov membunuh seorang rentenir demi teori moralnya sendiri — dan perlahan dihancurkan oleh rasa bersalah yang tak tertanggungkan.",
    category: "lokal",
    tags: ["sastra", "fiksi", "psikologi", "klasik", "terjemahan"],
  },
  {
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    cover_url: OL_COVER("9780061935466"), open_library_id: "OL2798721W", total_pages: 336,
    description: "Scout Finch menyaksikan ayahnya, pengacara Atticus, membela pria kulit hitam yang dituduh tanpa bukti di Alabama selatan.",
    category: "lokal",
    tags: ["sastra", "fiksi", "keadilan", "klasik", "terjemahan"],
  },
  {
    title: "Pride and Prejudice",
    author: "Jane Austen",
    cover_url: OL_COVER("9780141439518"), open_library_id: "OL66554W", total_pages: 432,
    description: "Elizabeth Bennet bertemu Mr. Darcy yang sombong dan kaya. Romansa klasik yang mengkritik prasangka sosial dengan kecerdasan dan humor.",
    category: "lokal",
    tags: ["sastra", "romance", "klasik", "terjemahan"],
  },
  {
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    cover_url: OL_COVER("9780743273565"), open_library_id: "OL2657873W", total_pages: 208,
    description: "Jay Gatsby yang misterius dan kaya mengejar mimpi yang sudah berlalu di antara kemewahan dan kehampaan Amerika era 1920-an.",
    category: "lokal",
    tags: ["sastra", "fiksi", "klasik", "terjemahan"],
  },
  {
    title: "Brave New World",
    author: "Aldous Huxley",
    cover_url: OL_COVER("9780060850524"), open_library_id: "OL65669W", total_pages: 311,
    description: "Dunia masa depan di mana manusia diproduksi massal dan kebahagiaan dipaksakan. Distopia tentang bahaya stabilitas di atas kebebasan.",
    category: "lokal",
    tags: ["fiksi", "distopia", "sains", "terjemahan"],
  },
  {
    title: "Les Misérables",
    author: "Victor Hugo",
    cover_url: OL_COVER("9780451419439"), open_library_id: "OL166545W", total_pages: 1488,
    description: "Jean Valjean, mantan narapidana yang bertobat, menjalani hidup baru yang terus dibayangi oleh Inspektur Javert. Epos tentang keadilan dan penebusan.",
    category: "lokal",
    tags: ["sastra", "fiksi", "sejarah", "klasik", "terjemahan"],
  },
  {
    title: "The Stranger",
    author: "Albert Camus",
    cover_url: OL_COVER("9780679720201"), open_library_id: "OL38788W", total_pages: 159,
    description: "Meursault membunuh seorang Arab tanpa alasan jelas dan menghadapi pengadilan tanpa emosi. Novel absurdisme Camus yang mengusik pikiran.",
    category: "lokal",
    tags: ["sastra", "filsafat", "absurdisme", "terjemahan"],
  },

  /* ─── Non-Fiksi Internasional Tambahan ─── */
  {
    title: "How to Win Friends and Influence People",
    author: "Dale Carnegie",
    cover_url: OL_COVER("9780671027032"), open_library_id: "OL7432229W", total_pages: 320,
    description: "Buku komunikasi dan hubungan manusia yang paling banyak dibaca sepanjang masa — prinsip-prinsip sederhana membangun relasi yang tulus.",
    category: "lokal",
    tags: ["non-fiksi", "komunikasi", "pengembangan diri", "terjemahan"],
  },
  {
    title: "Think and Grow Rich",
    author: "Napoleon Hill",
    cover_url: OL_COVER("9781585424337"), open_library_id: "OL7196072W", total_pages: 320,
    description: "13 prinsip kesuksesan yang dirangkum dari wawancara ratusan orang terkaya Amerika. Klasik motivasi bisnis sejak 1937.",
    category: "lokal",
    tags: ["non-fiksi", "bisnis", "pengembangan diri", "terjemahan"],
  },
  {
    title: "The 48 Laws of Power",
    author: "Robert Greene",
    cover_url: OL_COVER("9780140280197"), open_library_id: "OL15390W", total_pages: 480,
    description: "48 hukum kekuasaan yang dipelajari dari sejarah para pemimpin, strategi, dan tirani — buku tentang kekuatan manusia yang kontroversial.",
    category: "lokal",
    tags: ["non-fiksi", "strategi", "sejarah", "terjemahan"],
  },
  {
    title: "Ego Is the Enemy",
    author: "Ryan Holiday",
    cover_url: OL_COVER("9781591847816"), open_library_id: "OL27292078W", total_pages: 256,
    description: "Ego adalah musuh terbesar ambisi kita — pelajaran dari Marcus Aurelius, Howard Hughes, dan para pemimpin besar tentang kerendahan hati.",
    category: "lokal",
    tags: ["non-fiksi", "filsafat", "pengembangan diri", "terjemahan"],
  },
  {
    title: "Digital Minimalism",
    author: "Cal Newport",
    cover_url: OL_COVER("9780525536512"), open_library_id: "OL27358956W", total_pages: 304,
    description: "Filosofi penggunaan teknologi dengan niat — pilih dengan cermat alat digital yang benar-benar mendukung nilai hidupmu.",
    category: "lokal",
    tags: ["non-fiksi", "produktivitas", "teknologi", "terjemahan"],
  },
  {
    title: "Range: Why Generalists Triumph",
    author: "David Epstein",
    cover_url: OL_COVER("9780735214484"), open_library_id: "OL27358950W", total_pages: 352,
    description: "Berlawanan dengan teori 10.000 jam — generalis yang mencoba banyak bidang justru lebih siap menghadapi dunia yang kompleks.",
    category: "lokal",
    tags: ["non-fiksi", "psikologi", "pengembangan diri", "terjemahan"],
  },
  {
    title: "Educated",
    author: "Tara Westover",
    cover_url: OL_COVER("9780399590504"), open_library_id: "OL27303548W", total_pages: 352,
    description: "Tara tumbuh di keluarga survivalist Idaho tanpa pendidikan formal — hingga ia berhasil masuk Cambridge dan Harvard dengan kemampuannya sendiri.",
    category: "lokal",
    tags: ["non-fiksi", "biografi", "pendidikan", "terjemahan"],
  },
  {
    title: "Becoming",
    author: "Michelle Obama",
    cover_url: OL_COVER("9781524763138"), open_library_id: "OL27316777W", total_pages: 448,
    description: "Memoar mantan First Lady Amerika yang menceritakan perjalanannya dari South Side Chicago hingga Gedung Putih — tentang identitas dan tujuan.",
    category: "lokal",
    tags: ["non-fiksi", "biografi", "inspirasi", "terjemahan"],
  },
  {
    title: "The Power of Habit",
    author: "Charles Duhigg",
    cover_url: OL_COVER("9781400069286"), open_library_id: "OL25641938W", total_pages: 371,
    description: "Ilmu di balik kebiasaan manusia dan organisasi — cue, routine, reward — dan bagaimana kita bisa mengubahnya secara sadar.",
    category: "lokal",
    tags: ["non-fiksi", "psikologi", "pengembangan diri", "terjemahan"],
  },
  {
    title: "Grit: The Power of Passion and Perseverance",
    author: "Angela Duckworth",
    cover_url: OL_COVER("9781501111105"), open_library_id: "OL27292072W", total_pages: 352,
    description: "Riset Angela Duckworth membuktikan bahwa bakat bukanlah segalanya — kombinasi passion dan ketekunan (grit) jauh lebih menentukan kesuksesan.",
    category: "lokal",
    tags: ["non-fiksi", "psikologi", "pengembangan diri", "terjemahan"],
  },
  {
    title: "Quiet: The Power of Introverts",
    author: "Susan Cain",
    cover_url: OL_COVER("9780307352149"), open_library_id: "OL25562097W", total_pages: 368,
    description: "Satu dari tiga orang adalah introvert. Susan Cain mengungkap kekuatan tersembunyi mereka dan mengapa dunia butuh keduanya.",
    category: "lokal",
    tags: ["non-fiksi", "psikologi", "pengembangan diri", "terjemahan"],
  },
];

export const KATEGORI = [
  { key: "fiksi", label: "Fiksi", emoji: "📖", subject: "fiction" },
  { key: "non-fiksi", label: "Non-Fiksi", emoji: "📚", subject: "nonfiction" },
  { key: "pengembangan-diri", label: "Pengembangan Diri", emoji: "🌱", subject: "self_help" },
  { key: "bisnis", label: "Bisnis & Ekonomi", emoji: "💼", subject: "business_economics" },
  { key: "biografi", label: "Biografi", emoji: "👤", subject: "biography" },
  { key: "sejarah", label: "Sejarah", emoji: "🏛️", subject: "history" },
  { key: "agama", label: "Agama & Spiritualitas", emoji: "🕌", subject: "religion" },
  { key: "sains", label: "Sains & Teknologi", emoji: "🔬", subject: "science" },
  { key: "novel", label: "Novel", emoji: "✍️", subject: "novel" },
  { key: "komik", label: "Komik & Manga", emoji: "🎨", subject: "comics" },
] as const;

export type KategoriKey = typeof KATEGORI[number]["key"];
