export type CuratedBook = {
  title: string;
  author: string;
  cover_url: string | null;
  open_library_id: string | null;
  total_pages: number | null;
  description: string;
  category: "anak" | "lokal";
  tags: string[];
};

// Covers via OpenLibrary ISBN API — null for books without known ISBN
const OL_COVER = (isbn: string) =>
  `https://covers.openlibrary.org/b/isbn/${isbn}-M.jpg`;

export const BUKU_ANAK: CuratedBook[] = [
  {
    title: "Harry Potter dan Batu Bertuah",
    author: "J.K. Rowling",
    cover_url: OL_COVER("9780439708180"),
    open_library_id: "OL82538W",
    total_pages: 368,
    description: "Harry Potter, bocah yatim piatu yang hidup bersama paman dan bibinya, menemukan bahwa dirinya adalah penyihir dan diundang masuk ke Sekolah Sihir Hogwarts.",
    category: "anak",
    tags: ["fantasi", "petualangan"],
  },
  {
    title: "Matilda",
    author: "Roald Dahl",
    cover_url: OL_COVER("9780142410370"),
    open_library_id: "OL26745W",
    total_pages: 240,
    description: "Matilda adalah gadis kecil yang sangat cerdas namun diabaikan keluarganya. Ia menemukan bahwa dirinya memiliki kekuatan telekinetik yang luar biasa.",
    category: "anak",
    tags: ["petualangan", "humor"],
  },
  {
    title: "Charlie dan Pabrik Cokelat",
    author: "Roald Dahl",
    cover_url: OL_COVER("9780142410318"),
    open_library_id: "OL36741W",
    total_pages: 176,
    description: "Charlie Bucket memenangkan Golden Ticket dan diajak masuk ke pabrik cokelat milik Willy Wonka yang penuh keajaiban.",
    category: "anak",
    tags: ["petualangan", "humor"],
  },
  {
    title: "Kancil dan Buaya",
    author: "Cerita Rakyat Indonesia",
    cover_url: null,
    open_library_id: null,
    total_pages: 48,
    description: "Kisah Si Kancil yang cerdik berhasil menyeberangi sungai dengan cara mengelabui para buaya. Cerita rakyat Nusantara yang mengajarkan akal dan kecerdikan.",
    category: "anak",
    tags: ["cerita rakyat", "fabel"],
  },
  {
    title: "Timun Mas",
    author: "Cerita Rakyat Indonesia",
    cover_url: null,
    open_library_id: null,
    total_pages: 48,
    description: "Seorang gadis bernama Timun Mas harus kabur dari raksasa menggunakan benda-benda ajaib pemberian ibunya. Legenda Jawa yang penuh pesan moral.",
    category: "anak",
    tags: ["cerita rakyat", "legenda"],
  },
  {
    title: "Bawang Merah dan Bawang Putih",
    author: "Cerita Rakyat Indonesia",
    cover_url: null,
    open_library_id: null,
    total_pages: 48,
    description: "Perbandingan antara Bawang Putih yang baik hati dengan Bawang Merah yang dengki. Cerita rakyat Indonesia yang mengajarkan kebaikan dan kejujuran.",
    category: "anak",
    tags: ["cerita rakyat", "moral"],
  },
  {
    title: "The Very Hungry Caterpillar",
    author: "Eric Carle",
    cover_url: OL_COVER("9780399226908"),
    open_library_id: "OL27258W",
    total_pages: 32,
    description: "Seekor ulat kecil yang lapar makan berbagai makanan selama seminggu sebelum akhirnya berubah menjadi kupu-kupu cantik.",
    category: "anak",
    tags: ["picture book", "edukasi"],
  },
  {
    title: "Laskar Pelangi Versi Anak",
    author: "Andrea Hirata",
    cover_url: null,
    open_library_id: null,
    total_pages: 120,
    description: "Adaptasi untuk anak-anak dari kisah persahabatan dan semangat sekolah sepuluh anak Belitung yang menginspirasi.",
    category: "anak",
    tags: ["Indonesia", "inspirasi"],
  },
  {
    title: "Si Kancil Anak Nakal",
    author: "Murti Bunanta",
    cover_url: null,
    open_library_id: null,
    total_pages: 56,
    description: "Petualangan Si Kancil yang nakal namun cerdas dalam menghadapi berbagai situasi di hutan Nusantara.",
    category: "anak",
    tags: ["fabel", "Indonesia"],
  },
  {
    title: "Malin Kundang",
    author: "Cerita Rakyat Sumatera Barat",
    cover_url: null,
    open_library_id: null,
    total_pages: 48,
    description: "Kisah anak durhaka yang dikutuk menjadi batu oleh ibunya. Legenda Sumatera Barat yang mengajarkan pentingnya bakti kepada orang tua.",
    category: "anak",
    tags: ["legenda", "moral"],
  },
  {
    title: "Aku Bisa! Seri Pertumbuhan Karakter",
    author: "Watiek Ideo",
    cover_url: null,
    open_library_id: null,
    total_pages: 32,
    description: "Seri buku anak tentang pembentukan karakter positif: jujur, disiplin, dan berani mencoba hal baru.",
    category: "anak",
    tags: ["edukasi", "karakter"],
  },
  {
    title: "Diary of a Wimpy Kid",
    author: "Jeff Kinney",
    cover_url: OL_COVER("9780810993136"),
    open_library_id: "OL12718837W",
    total_pages: 224,
    description: "Catatan harian Greg Heffley yang lucu tentang pengalamannya di sekolah menengah pertama, penuh kejadian konyol dan pelajaran hidup.",
    category: "anak",
    tags: ["humor", "remaja"],
  },
];

export const BUKU_LOKAL: CuratedBook[] = [
  {
    title: "Laskar Pelangi",
    author: "Andrea Hirata",
    cover_url: null,
    open_library_id: null,
    total_pages: 534,
    description: "Kisah sepuluh anak dari keluarga miskin di Belitung yang berjuang mendapatkan pendidikan terbaik dengan semangat yang tak pernah padam.",
    category: "lokal",
    tags: ["fiksi", "inspirasi", "pendidikan"],
  },
  {
    title: "Bumi Manusia",
    author: "Pramoedya Ananta Toer",
    cover_url: null,
    open_library_id: null,
    total_pages: 368,
    description: "Novel pertama Tetralogi Buru. Kisah Minke, pemuda Jawa terpelajar yang jatuh cinta pada Annelies di tengah kolonialisme Belanda.",
    category: "lokal",
    tags: ["fiksi", "sejarah", "sastra"],
  },
  {
    title: "Negeri 5 Menara",
    author: "Ahmad Fuadi",
    cover_url: null,
    open_library_id: null,
    total_pages: 423,
    description: "Alif Fikri, seorang anak Minang, mengikuti pendidikan di pesantren modern Gontor dan menemukan mimpi besar bersama sahabat-sahabatnya.",
    category: "lokal",
    tags: ["fiksi", "inspirasi", "pendidikan"],
  },
  {
    title: "Perahu Kertas",
    author: "Dewi Lestari (Dee)",
    cover_url: null,
    open_library_id: null,
    total_pages: 444,
    description: "Kisah cinta Kugy dan Keenan yang ditemukan kembali lewat perahu kertas mimpi dan seni, menembus waktu dan jarak.",
    category: "lokal",
    tags: ["fiksi", "romance"],
  },
  {
    title: "Supernova: Ksatria, Puteri, dan Bintang Jatuh",
    author: "Dewi Lestari (Dee)",
    cover_url: null,
    open_library_id: null,
    total_pages: 328,
    description: "Novel sains populer Indonesia yang memadukan fisika kuantum, spiritualitas, dan kisah cinta yang kompleks.",
    category: "lokal",
    tags: ["fiksi", "sains", "filsafat"],
  },
  {
    title: "Dilan: Dia adalah Dilanku Tahun 1990",
    author: "Pidi Baiq",
    cover_url: null,
    open_library_id: null,
    total_pages: 231,
    description: "Kisah cinta SMA di Bandung tahun 1990 antara Milea dan Dilan, pemuda geng motor yang romantis dan jenaka.",
    category: "lokal",
    tags: ["romance", "remaja"],
  },
  {
    title: "Tentang Kamu",
    author: "Tere Liye",
    cover_url: null,
    open_library_id: null,
    total_pages: 524,
    description: "Perjalanan pengacara muda menemukan kisah hidup Sri Ningsih, wanita Indonesia yang menjalani berbagai babak kehidupan di berbagai belahan dunia.",
    category: "lokal",
    tags: ["fiksi", "drama"],
  },
  {
    title: "Cantik Itu Luka",
    author: "Eka Kurniawan",
    cover_url: null,
    open_library_id: null,
    total_pages: 505,
    description: "Kisah keluarga Dewi Ayu dan tiga putrinya yang terjerat kutukan kecantikan, berlatar sejarah Indonesia dari masa penjajahan hingga kemerdekaan.",
    category: "lokal",
    tags: ["sastra", "sejarah", "fiksi"],
  },
  {
    title: "5 Cm",
    author: "Donny Dhirgantoro",
    cover_url: null,
    open_library_id: null,
    total_pages: 381,
    description: "Lima sahabat menapaki puncak Mahameru dengan tekad bahwa impian harus diletakkan di depan mata, sejauh 5 cm dari kening.",
    category: "lokal",
    tags: ["petualangan", "persahabatan"],
  },
  {
    title: "Pulang",
    author: "Leila S. Chudori",
    cover_url: null,
    open_library_id: null,
    total_pages: 464,
    description: "Kisah para eksil Indonesia di Paris yang tidak bisa pulang ke tanah air akibat tragedi 1965, dituturkan lintas generasi.",
    category: "lokal",
    tags: ["sastra", "sejarah", "fiksi"],
  },
  {
    title: "Ayah",
    author: "Andrea Hirata",
    cover_url: null,
    open_library_id: null,
    total_pages: 412,
    description: "Kisah cinta seorang ayah kepada putrinya, Amiru, yang ia besarkan dengan cara yang unik dan penuh kasih di tanah Belitung.",
    category: "lokal",
    tags: ["fiksi", "keluarga"],
  },
  {
    title: "Atomic Habits (Terjemahan)",
    author: "James Clear",
    cover_url: OL_COVER("9780735211292"),
    open_library_id: "OL20082940W",
    total_pages: 320,
    description: "Panduan praktis membentuk kebiasaan baik dan menghilangkan kebiasaan buruk melalui perubahan kecil yang konsisten.",
    category: "lokal",
    tags: ["non-fiksi", "pengembangan diri"],
  },
  {
    title: "Rich Dad Poor Dad (Terjemahan)",
    author: "Robert T. Kiyosaki",
    cover_url: OL_COVER("9781612680194"),
    open_library_id: "OL2682688W",
    total_pages: 336,
    description: "Pelajaran keuangan yang diajarkan oleh dua ayah dengan filosofi berbeda tentang uang, investasi, dan kebebasan finansial.",
    category: "lokal",
    tags: ["non-fiksi", "bisnis", "keuangan"],
  },
];

export const KATEGORI = [
  { key: "fiksi", label: "Fiksi", emoji: "📖", subject: "fiction" },
  { key: "non-fiksi", label: "Non-Fiksi", emoji: "📚", subject: "nonfiction" },
  { key: "pengembangan-diri", label: "Pengembangan Diri", emoji: "🌱", subject: "self_help" },
  { key: "bisnis", label: "Bisnis & Ekonomi", emoji: "💼", subject: "business_economics" },
  { key: "biografi", label: "Biografi", emoji: "👤", subject: "biography" },
  { key: "sejarah", label: "Sejarah", emoji: "🏛️", subject: "history" },
  { key: "agama", label: "Agama & Spiritualitas", emoji: "🕌", subject: "religion" },
  { key: "sains", label: "Sains & Teknologi", emoji: "🔬", subject: "science" },
  { key: "novel", label: "Novel", emoji: "✍️", subject: "novel" },
  { key: "komik", label: "Komik & Manga", emoji: "🎨", subject: "comics" },
] as const;

export type KategoriKey = typeof KATEGORI[number]["key"];
